name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build documentation
        run: |
          # Create a build directory for GitHub Pages
          mkdir -p _site

          # Copy documentation files
          cp -r docs/* _site/

          # Create a simple demo using the built library
          mkdir -p _site/live-demo

          # Copy built library files for live demo
          cp dist/simplify-captcha.js _site/live-demo/
          cp dist/simplify-captcha.umd.cjs _site/live-demo/

          # Create a live demo page
          cat > _site/live-demo/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>SimplifyCaptcha - Live Demo</title>
              <script src="https://unpkg.com/react@18/umd/react.development.js"></script>
              <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
              <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
              <link href="../styles.css" rel="stylesheet">
              <style>
                  body { 
                      font-family: 'Inter', sans-serif; 
                      padding: 2rem; 
                      background: #f8fafc;
                  }
                  .demo-container { 
                      max-width: 800px; 
                      margin: 0 auto; 
                      background: white; 
                      padding: 2rem; 
                      border-radius: 12px; 
                      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                  }
                  .back-link { 
                      color: #48d1cc; 
                      text-decoration: none; 
                      margin-bottom: 2rem; 
                      display: inline-block;
                  }
                  .demo-area {
                      border: 2px dashed #d1d5db;
                      border-radius: 8px;
                      padding: 2rem;
                      text-align: center;
                      margin: 2rem 0;
                  }
              </style>
          </head>
          <body>
              <div class="demo-container">
                  <a href="../" class="back-link">← Back to Documentation</a>
                  <h1>SimplifyCaptcha Live Demo</h1>
                  <p>This is a live demo using the actual SimplifyCaptcha library.</p>
                  
                  <div id="react-demo" class="demo-area">
                      <p>Loading React demo...</p>
                  </div>
                  
                  <div class="note">
                      <h3>Note:</h3>
                      <p>This live demo uses the built library directly. In a real application, you would install via npm and import the components.</p>
                  </div>
              </div>
              
              <script type="text/babel">
                  // This would normally be imported from the npm package
                  // For demo purposes, we'll create a simple placeholder
                  function SimplifyCaptchaDemo() {
                      const [showCaptcha, setShowCaptcha] = React.useState(false);
                      const [result, setResult] = React.useState('');
                      
                      return (
                          <div>
                              <h3>Interactive Demo</h3>
                              <p>Click the button below to test the CAPTCHA component:</p>
                              
                              <button 
                                  onClick={() => setShowCaptcha(true)}
                                  style={{
                                      background: '#48d1cc',
                                      color: 'white',
                                      border: 'none',
                                      padding: '0.75rem 2rem',
                                      borderRadius: '8px',
                                      cursor: 'pointer',
                                      fontSize: '1rem',
                                      fontWeight: '600'
                                  }}
                              >
                                  Show CAPTCHA
                              </button>
                              
                              {showCaptcha && (
                                  <div style={{
                                      marginTop: '2rem',
                                      padding: '2rem',
                                      background: '#f8fafc',
                                      borderRadius: '8px',
                                      border: '1px solid #e5e7eb'
                                  }}>
                                      <div style={{ textAlign: 'center' }}>
                                          <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>🔒</div>
                                          <h4>CAPTCHA Verification</h4>
                                          <p>This is a demo placeholder. The actual component would analyze your behavior here.</p>
                                          <button 
                                              onClick={() => {
                                                  setResult('✅ Verified! You are human.');
                                                  setTimeout(() => setShowCaptcha(false), 2000);
                                              }}
                                              style={{
                                                  background: '#10b981',
                                                  color: 'white',
                                                  border: 'none',
                                                  padding: '0.5rem 1rem',
                                                  borderRadius: '6px',
                                                  cursor: 'pointer',
                                                  margin: '0.5rem'
                                              }}
                                          >
                                              Simulate Success
                                          </button>
                                          <button 
                                              onClick={() => setShowCaptcha(false)}
                                              style={{
                                                  background: '#6b7280',
                                                  color: 'white',
                                                  border: 'none',
                                                  padding: '0.5rem 1rem',
                                                  borderRadius: '6px',
                                                  cursor: 'pointer',
                                                  margin: '0.5rem'
                                              }}
                                          >
                                              Cancel
                                          </button>
                                      </div>
                                  </div>
                              )}
                              
                              {result && (
                                  <div style={{
                                      marginTop: '1rem',
                                      padding: '1rem',
                                      background: '#d1fae5',
                                      border: '1px solid #10b981',
                                      borderRadius: '6px',
                                      color: '#065f46'
                                  }}>
                                      {result}
                                  </div>
                              )}
                          </div>
                      );
                  }
                  
                  ReactDOM.render(<SimplifyCaptchaDemo />, document.getElementById('react-demo'));
              </script>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
